import '@aws-amplify/ui-react/styles.css';
import { ChakraProvider } from '@chakra-ui/react';
import { Inter } from 'next/font/google';
import './globals.css';
import ConfigureAmplifyClientSide from './utils/ConfigureAmplifyClientSide';
import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ConfigureAmplifyClientSide />
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  );
}
