name: plant-eatery_CI/CD

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Run lint&prettier
      run: npm run fix

  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to server
      run: |
        # AWSリソース周りの構築が完了した時に記述予定
        # 例: AWS S3:
        # aws s3 sync build/ s3://your-bucket-name
